site_name: TAQ

nav:
  - Accueil: index.md
  - Cours:
      - Secondes:
          - Accueil: Secondes/Secondes.md
          - Exposés: Secondes/exposes.md
          - Internet : Secondes/Chapitres/Internet/Internet.md
          - Réseaux sociaux : Secondes/Chapitres/RS/RS.md
      - Premières:
          - Accueil: Premieres/Premieres.md
          - Types de base (entiers): Premieres/Chapitres/Types_de_base_int.md
          - Types de base (flottants): Premieres/Chapitres/Types_de_base_float.md
          - Types de base (booléens): Premieres/Chapitres/Types_de_base_bool.md
          - Types de base (chaînes de caractéres): Premieres/Chapitres/Types_de_base_str.md
          - Types construits (tuples): Premieres/Chapitres/Tuples.md
          - Types construits (tableaux): Premieres/Chapitres/Tableaux.md
          - Types construits (dictionnaires): Premieres/Chapitres/Dictionnaires.md
          - Réseaux: Premieres/Chapitres/Réseaux/Réseaux.md
      - Terminales:
          - Accueil: Terminales/Terminales.md
          - Programmation Orientée Objet: Terminales/Chapitres/POO.md
          - Piles et Files: Terminales/Chapitres/Piles&Files/Piles&Files.md
          - Base de données: Terminales/Chapitres/BDD.md


theme:
  name: readthedocs
  toc:
    include: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
