site_name: TAQ

nav:
  - Accueil: index.md
  - Cours:
      - Secondes:
          - Accueil: Secondes/Secondes.md
          - Exposés: Secondes/exposes.md
          - Internet : Secondes/Chapitres/Internet/Internet.md
          - Réseaux sociaux : Secondes/Chapitres/RS/RS.md
      - Premières:
          - Accueil: Premieres/Premieres.md
          - Types de base: Premieres/Chapitres/Types/Types_de_base.md
          - Bases de Python: Premieres/Chapitres/Bases/bases.md
          - Tuples, Listes et Dictionnaires: Premieres/Chapitres/Tableaux/Tableaux.md
          - Réseaux: Premieres/Chapitres/Réseaux/Réseaux.md
          - Algorithmes: Premieres/Chapitres/Algos/Algos.md 
      - Terminales:
          - Accueil: Terminales/Terminales.md
          - Programmation Orientée Objet: Terminales/Chapitres/POO.md
          - Piles et Files: Terminales/Chapitres/Piles&Files/Piles&Files.md
          - Base de données: Terminales/Chapitres/BDD.md
          - Algorithmes de Routage: Terminales/Chapitres/Routage/routage.md


theme:
  name: readthedocs
  toc:
    include: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
